# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindows.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLCDNumber, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        icon = QIcon()
        icon.addFile(u":/images/assets/images/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(683, 683))
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(1070, 3, 61, 17))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(1130, 3, 61, 17))
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(1200, 3, 17, 17))
        self.label_23.setPixmap(QPixmap(u":/images/assets/images/wifi_0.png"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(1220, 4, 71, 17))
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(880, 0, 100, 24))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(530, 0, 3, 687))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(12, 12, 144, 22))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(491, 12, 34, 22))
        self.label_2.setFont(font1)
        self.lcdNumber = QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(421, 12, 64, 23))
        font2 = QFont()
        font2.setPointSize(10)
        self.lcdNumber.setFont(font2)
        self.lcdNumber.setMode(QLCDNumber.Mode.Dec)
        self.lcdNumber.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber.setProperty(u"value", 0.000000000000000)
        self.lcdNumber.setProperty(u"intValue", 0)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(490, 60, 34, 22))
        self.label_4.setFont(font1)
        self.lcdNumber_2 = QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(420, 60, 64, 23))
        self.lcdNumber_2.setFont(font2)
        self.lcdNumber_2.setMode(QLCDNumber.Mode.Dec)
        self.lcdNumber_2.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_2.setProperty(u"value", 0.000000000000000)
        self.lcdNumber_2.setProperty(u"intValue", 0)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(12, 60, 255, 22))
        self.label_3.setFont(font1)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QRect(10, 479, 250, 171))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy2)
        font3 = QFont()
        font3.setPointSize(40)
        font3.setBold(True)
        self.pushButton.setFont(font3)
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 0, 0); /* \u6309\u4e0b\u65f6\u80cc\u666f\u53d8\u4e3a\u4eae\u7ea2\u8272 */\n"
"}\n"
"")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(270, 480, 250, 171))
        sizePolicy2.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy2)
        self.pushButton_2.setFont(font3)
        self.pushButton_2.setStyleSheet(u"QPushButton {\n"
"    background-color: rgb(0, 170, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 255, 0); \n"
"}\n"
"")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(12, 122, 144, 22))
        self.label_5.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(450, 150, 80, 30))
        font4 = QFont()
        font4.setPointSize(17)
        font4.setBold(True)
        self.label_7.setFont(font4)
        self.horizontalSlider = QSlider(self.centralwidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(13, 159, 421, 16))
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(12, 193, 221, 22))
        self.label_6.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(450, 223, 80, 30))
        self.label_8.setFont(font4)
        self.horizontalSlider_2 = QSlider(self.centralwidget)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(13, 230, 421, 16))
        self.horizontalSlider_2.setMinimum(-100)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(450, 330, 80, 30))
        self.label_15.setFont(font4)
        self.horizontalSlider_4 = QSlider(self.centralwidget)
        self.horizontalSlider_4.setObjectName(u"horizontalSlider_4")
        self.horizontalSlider_4.setEnabled(False)
        self.horizontalSlider_4.setGeometry(QRect(13, 336, 421, 16))
        self.horizontalSlider_4.setMinimum(-100)
        self.horizontalSlider_4.setMaximum(100)
        self.horizontalSlider_4.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_4.setInvertedAppearance(False)
        self.radioButton = QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(260, 294, 145, 26))
        self.radioButton.setFont(font1)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(14, 294, 195, 22))
        self.label_13.setFont(font1)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(12, 373, 272, 22))
        self.label_14.setFont(font1)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(450, 405, 80, 30))
        self.label_16.setFont(font4)
        self.horizontalSlider_3 = QSlider(self.centralwidget)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setEnabled(False)
        self.horizontalSlider_3.setGeometry(QRect(13, 410, 421, 16))
        self.horizontalSlider_3.setMinimum(-100)
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setOrientation(Qt.Orientation.Horizontal)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(531, 300, 750, 3))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(700, 3, 39, 17))
        self.label_20.setFont(font)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(800, 0, 75, 24))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(540, 3, 16, 17))
        self.label_19.setFont(font)
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QRect(560, 3, 131, 20))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(745, 3, 51, 20))
        self.webEngineView = QWebEngineView(self.centralwidget)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(540, 350, 731, 331))
        self.webEngineView.setUrl(QUrl(u"about:blank"))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(940, 309, 75, 20))
        font5 = QFont()
        font5.setBold(True)
        self.pushButton_3.setFont(font5)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(540, 310, 53, 17))
        self.label_9.setFont(font)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(610, 310, 121, 17))
        self.label_11.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(540, 330, 39, 17))
        self.label_10.setFont(font)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(610, 330, 121, 17))
        self.label_12.setFont(font)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(730, 330, 52, 17))
        self.label_18.setFont(font)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(790, 330, 16, 16))
        self.comboBox = QComboBox(self.centralwidget)
        icon1 = QIcon()
        icon1.addFile(u":/images/assets/images/ip-address.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox.addItem(icon1, "")
        icon2 = QIcon()
        icon2.addFile(u":/images/assets/images/satellite.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QIcon()
        icon3.addFile(u":/images/assets/images/images.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox.addItem(icon3, "")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(830, 309, 105, 20))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(730, 310, 91, 17))
        self.label_17.setFont(font)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(985, 0, 75, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1280, 33))
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menuBar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GPS Robot", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u5168\u753b\u9762\u8868\u793a", None))
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u30fc\u306e\u8a2d\u5b9a", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u30bd\u30d5\u30c8\u30a6\u30a7\u30a2\u306b\u3064\u3044\u3066", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u30bd\u30d5\u30c8\u30a6\u30a7\u30a2\u3092\u7d42\u4e86\u3059\u308b", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u672a\u63a5\u7d9a", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"9999ms", None))
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"-99dBm", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u30aa\u30fc\u30c8\u30b9\u30ad\u30e3\u30f3", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"DC\u30e2\u30fc\u30bf\u30fc\u306e\u901f\u5ea6", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"m/s", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u" \u00b0/s", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u30b9\u30c6\u30c3\u30d4\u30f3\u30b0\u30e2\u30fc\u30bf\u30fc\u306e\u56de\u8ee2\u901f\u5ea6", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u975e\u5e38\u505c\u6b62\n"
"\u30dc\u30bf\u30f3", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u30b9\u30bf\u30fc\u30c8", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"DC\u30e2\u30fc\u30bf\u30fc\u306e\u611f\u5ea6", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u30b9\u30c6\u30c3\u30d4\u30f3\u30b0\u30e2\u30fc\u30bf\u30fc\u306e\u611f\u5ea6", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"\u624b\u52d5\u5236\u5fa1\u6709\u52b9\u5316", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"DC\u30e2\u30fc\u30bf\u30fc\u901f\u5ea6\u624b\u52d5\u5236\u5fa1", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u30b9\u30c6\u30c3\u30d4\u30f3\u30b0\u30e2\u30fc\u30bf\u30fc\u901f\u5ea6\u624b\u52d5\u5236\u5fa1", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u30dd\u30fc\u30c8", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u7d9a\u3059\u308b", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u624b\u52d5\u66f4\u65b0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPS\u6e2c\u4f4d", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"NONE", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"IP\u6e2c\u4f4d", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"NONE", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52d5\u66f4\u65b0", None))
        self.checkBox.setText("")
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"IP\u6e2c\u4f4d", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"GPS\u6e2c\u4f4d", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u5de5\u5b66\u90e8", None))

        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u5730\u56f3\u306e\u4e2d\u5fc3\u8a2d\u5b9a", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"BLE\u914d\u7db2", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u8a2d\u7f6e", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u30a2\u30d0\u30a6\u30c8", None))
    # retranslateUi

